# Generated by Django 3.2.7 on 2021-10-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesAdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='addimages/')),
                ('image_category', models.CharField(choices=[('Top-Banner', 'Top-Banner'), ('Blog-Post', 'Blog-Post'), ('Testimonials', 'Testimonials'), ('Card-Banner', 'Card-Banner')], default='None', max_length=20)),
            ],
        ),
    ]
